# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in_app', '0002_auto_20190222_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='messages',
        ),
        migrations.AddField(
            model_name='comments',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='log_in_app.messages'),
        ),
        migrations.RemoveField(
            model_name='messages',
            name='users',
        ),
        migrations.AddField(
            model_name='messages',
            name='users',
            field=models.ManyToManyField(related_name='users', to='log_in_app.users'),
        ),
    ]
