# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in_app', '0005_auto_20190222_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='messages',
            field=models.ManyToManyField(related_name='m_comments', to='log_in_app.Messages'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='users',
            field=models.ManyToManyField(related_name='u_comments', to='log_in_app.Users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='users',
            field=models.ManyToManyField(related_name='messages', to='log_in_app.Users'),
        ),
    ]
